project:
  type: website
  output-dir: docs

website:
  title: "Tina Rashid Jafari"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorials"
        menu:
          - text: "Tutorial 1: ETC1010"
            href: tutorials/ETC1010-tutorial1.html
            
  google-analytics: "G-85GWJNB5L8"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: 
  mode: source
  drafts:
    draft-mode: visible
    
date-format: DD MMM YYYY

